name: Label PR on close

on:
  pull_request:
    types: [closed]

permissions:
  pull-requests: write

jobs:
  label:
    if: |
      github.event.pull_request.merged == false &&
      !contains(github.event.pull_request.labels.*.name, 'successfully-deployed') &&
      !contains(github.event.pull_request.labels.*.name, 'failed-to-deploy')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Label as rejected
        run: |
          gh pr edit ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --remove-label "waiting-for-approval" \
            --add-label "rejected"
